services:
  postgres:
    image: postgres:16-bookworm
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auctions
    ports:
      - "5432:5432"
    volumes:
      - cars-data:/var/lib/postgresql/data
  
  mongo:
    image: mongo:7-jammy
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - cars-mongo-data:/var/lib/mongodb/data
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
        
  auction-svc:
    image: capricornpl/auction-svc:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgres;Database=auctions;
      - IdentityService__Authority=http://identity-svc
    ports:
      - "8000:80"
    depends_on:
      - postgres
      - rabbitmq
      # - identity-svc
  
  search-svc:
    image: capricornpl/search-svc:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__MongoDb=mongodb://root:password@mongo:27017
      - IdentityService__Authority=http://identity-svc
    ports:
      - "8001:80"
    depends_on:
      - mongo
      - rabbitmq
      # - identity-svc

volumes:
  cars-data:
  cars-mongo-data: