version: "3.8"

services:
  postgres:
    image: postgres:16-bookworm
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auctions
    ports:
      - "5432:5432"
    volumes:
      - cars-data:/var/lib/postgresql/data

volumes:
    cars-data: