name: deploy-identity-svc

on:
  workflow_dispatch:  
  push:
    branches: [ "main" ]
    paths:
      - "src/IdentityService/**"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .false
          file: src/IdentityService/Dockerfile
          push: true
          tags: capricornpl/identity-svc:latest
